### ISSUE TITLE
why can you archive High concurrency

### ISSUE THREAD

**Issue by fizz12344321** [vlingo/xoom-actors#97]
Hi, i am reading your project and i am interesting it, but i have a question, why can you archive High concurrency in your app, can you tell me how can you do it, the pros and cons when using it, thank u so much

**Comment by VaughnVernon** [comment]
@fizz12344321 Have you read our documentation?

https://docs.vlingo.io 

For very high throughput, see:

https://docs.vlingo.io/xoom-actors#mailbox

Specifically read the part under `"arrayQueueMailbox"`

**Comment by VaughnVernon** [comment]
This is a completely different platform that serves the contemporary use of DDD. To understand our vision please read our documentation, especially the introductory chapters.

**Comment by VaughnVernon** [comment]
@fizz12344321 My vision and that of our company is different from the libraries you reference. Actors reflect true objects as intended by Alan Kay, the originator of the term object-oriented and the Smalltalk language, because "the big idea is messaging" between discrete objects. This is a specific,  opinionated approach to software development and DDD.

I have spent a lot of time writing our documentation. I can't take time to rewrite it here. Here's also an ebook that you can download that offers more flavor than the documentation:

http://merge.kalele.io/books/rddd-book/

**Comment by VaughnVernon** [comment]
Chapters 1-4.

**Comment by VaughnVernon** [comment]
Check your spam folder for the confirmation download email message.
